Update Stringio
to play past:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/stringio-0.1.4/ext/stringio
/home/edavey/.rbenv/versions/3.3.6/bin/ruby extconf.rb
checking for rb_io_extract_modeenc() in ruby/io.h... yes
creating Makefile

current directory: /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/stringio-0.1.4/ext/stringio
make DESTDIR\= sitearchdir\=./.gem.20250128-697068-or7eox sitelibdir\=./.gem.20250128-697068-or7eox clean

current directory: /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/stringio-0.1.4/ext/stringio
make DESTDIR\= sitearchdir\=./.gem.20250128-697068-or7eox sitelibdir\=./.gem.20250128-697068-or7eox
compiling stringio.c
stringio.c: In function ‘strio_init’:
stringio.c:342:24: error: storage size of ‘convconfig’ isn’t known
  342 |     struct rb_io_enc_t convconfig;
      |                        ^~~~~~~~~~
stringio.c:342:24: warning: unused variable ‘convconfig’ [-Wunused-variable]
stringio.c: In function ‘Init_stringio’:
stringio.c:1801:50: error: ‘rb_cData’ undeclared (first use in this function)
 1801 |     VALUE StringIO = rb_define_class("StringIO", rb_cData);
      |                                                  ^~~~~~~~
stringio.c:1801:50: note: each undeclared identifier is reported only once for each function it appears in
At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
make: *** [Makefile:248: stringio.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/stringio-0.1.4 for inspection.
Results logged to /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/stringio-0.1.4/gem_make.out

  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:51:in `block in make'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `each'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `make'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/3.3.0/rubygems/installer.rb:844:in `build_extensions'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.3.23/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.3.23/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.3.23/lib/bundler/source/rubygems.rb:207:in `install'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.3.23/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.3.23/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.3.23/lib/bundler/worker.rb:62:in `apply_func'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.3.23/lib/bundler/worker.rb:57:in `block in process_queue'
  <internal:kernel>:187:in `loop'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.3.23/lib/bundler/worker.rb:54:in `process_queue'
  /home/edavey/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.3.23/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing stringio (0.1.4), and Bundler cannot continue.

In Gemfile:
  debug was resolved to 1.10.0, which depends on
    irb was resolved to 1.15.1, which depends on
      rdoc was resolved to 6.11.0, which depends on
        psych was resolved to 4.0.6, which depends on
          stringio