(Fix) Handle incomplete member details from the Parliamentary Members API
We were having an error on production related to an incomplete or missing
MP details record from the Parliamentary Members API:

```
undefined method `email' for nil:NilClass @member_contact_details.email
```

It seems the MP details are not totally missing, otherwise the guard on
`app/presenters/export/csv/mp_presenter_module.rb:9`
`Export::Csv::MpPresenterModule#mp_email`
would have caught it.

This fix should guard against the error reoccurring.